//! Matter Compiler
//! End-to-end compilation pipeline: Source → Lexer → Parser → AST → Bytecode
//!
//! Sprint 79: Compiler Pipeline Integration
//! Goal: Close the critical gap - make .matter files compile and run

use matter_ast::Program;
use matter_bytecode::{Bytecode, BytecodeBuilder};
use matter_lexer::Lexer;
use matter_parser::Parser;

/// Compilation error type
#[derive(Debug, Clone)]
pub enum CompilerError {
    LexerError(String),
    ParserError(String),
    BytecodeError(String),
}

impl std::fmt::Display for CompilerError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CompilerError::LexerError(s) => write!(f, "Lexer error: {}", s),
            CompilerError::ParserError(s) => write!(f, "Parser error: {}", s),
            CompilerError::BytecodeError(s) => write!(f, "Bytecode error: {}", s),
        }
    }
}

impl std::error::Error for CompilerError {}

/// Compilation result
pub struct CompilationResult {
    pub bytecode: Bytecode,
    pub warnings: Vec<String>,
}

/// Main compiler struct - integrates lexer, parser, and bytecode generation
pub struct Compiler {
    warnings: Vec<String>,
}

impl Compiler {
    pub fn new() -> Self {
        Self {
            warnings: Vec::new(),
        }
    }

    /// Compile source code to bytecode (end-to-end pipeline)
    pub fn compile(source: &str) -> Result<CompilationResult, CompilerError> {
        let mut compiler = Compiler::new();
        
        // Phase 1: Lexical Analysis
        let mut lexer = Lexer::new(source);
        let tokens = lexer.tokenize();
        
        // Phase 2: Syntax Analysis
        let mut parser = Parser::new(tokens);
        let program = parser.parse()
            .map_err(|e| CompilerError::ParserError(format!("{:?}", e)))?;
        
        // Phase 3: Bytecode Generation
        let bytecode = compiler.generate_bytecode(&program)?;
        
        Ok(CompilationResult {
            bytecode,
            warnings: compiler.warnings,
        })
    }

    /// Generate bytecode from AST using the existing BytecodeBuilder
    fn generate_bytecode(&mut self, program: &Program) -> Result<Bytecode, CompilerError> {
        let builder = BytecodeBuilder::new();
        
        // Use the existing, battle-tested BytecodeBuilder
        let bytecode = builder.build_checked(program)
            .map_err(|e| CompilerError::BytecodeError(e.message))?;
        
        Ok(bytecode)
    }

    /// Compile and check semantics (uses effect checking from bytecode crate)
    pub fn compile_checked(source: &str) -> Result<CompilationResult, CompilerError> {
        // This uses the same path but with semantic validation
        Self::compile(source)
    }
}

impl Default for Compiler {
    fn default() -> Self {
        Self::new()
    }
}

/// Convenience function: compile source to bytecode
pub fn compile(source: &str) -> Result<Bytecode, CompilerError> {
    let result = Compiler::compile(source)?;
    Ok(result.bytecode)
}

/// Convenience function: compile source to bytecode with validation
pub fn compile_checked(source: &str) -> Result<Bytecode, CompilerError> {
    let result = Compiler::compile_checked(source)?;
    Ok(result.bytecode)
}

#[cfg(test)]
mod tests {
    use super::*;
    use matter_bytecode::Instruction;

    #[test]
    fn compile_simple_expression() {
        let source = "1 + 2";
        let result = Compiler::compile(source).unwrap();
        
        // Should have: LoadConst(1), LoadConst(2), Add, Pop, Halt
        assert!(!result.bytecode.main_instructions.is_empty());
        assert!(matches!(result.bytecode.main_instructions[0], Instruction::LoadConst(_)));
    }

    #[test]
    fn compile_variable_declaration() {
        let source = "let x = 42";
        let result = Compiler::compile(source).unwrap();
        
        // Should have: LoadConst(42), StoreGlobal("x"), Halt
        assert!(result.bytecode.main_instructions.iter().any(
            |i| matches!(i, Instruction::StoreGlobal(name) if name == "x")
        ));
    }

    #[test]
    fn compile_function_definition() {
        let source = r#"
            fn add(a, b) {
                return a + b
            }
        "#;
        let result = Compiler::compile(source).unwrap();
        
        // Should have function "add" with 2 parameters
        assert!(result.bytecode.functions.contains_key("add"));
        assert_eq!(result.bytecode.functions["add"].param_count, 2);
    }

    #[test]
    fn compile_function_call() {
        let source = r#"
            fn double(x) { return x * 2 }
            let y = double(21)
        "#;
        let result = Compiler::compile(source).unwrap();
        
        // Should have function and call
        assert!(result.bytecode.functions.contains_key("double"));
        // The call will be generated by BytecodeBuilder
        assert!(!result.bytecode.main_instructions.is_empty());
    }

    #[test]
    fn compile_if_statement() {
        let source = r#"
            let x = 10
            if x > 5 {
                let y = 1
            } else {
                let y = 2
            }
        "#;
        let result = Compiler::compile(source).unwrap();
        
        // Should have conditional jumps
        assert!(result.bytecode.main_instructions.iter().any(
            |i| matches!(i, Instruction::JumpIfFalse(_))
        ));
    }

    #[test]
    fn compile_while_loop() {
        let source = r#"
            let i = 0
            loop {
                if i > 10 {
                    break
                }
                let j = i + 1
            }
        "#;
        let result = Compiler::compile(source).unwrap();
        
        // Should have jumps for loop
        assert!(result.bytecode.main_instructions.iter().any(
            |i| matches!(i, Instruction::Jump(_))
        ));
    }

    #[test]
    fn compile_for_loop() {
        let source = r#"
            for i in [1, 2, 3, 4, 5] {
                let x = i * 2
            }
        "#;
        let result = Compiler::compile(source).unwrap();
        
        // Should compile without errors
        assert!(!result.bytecode.main_instructions.is_empty());
    }

    #[test]
    fn compile_backend_call() {
        let source = r#"math.sqrt(16.0)"#;
        let result = Compiler::compile(source).unwrap();
        
        // Should have backend call
        assert!(result.bytecode.main_instructions.iter().any(
            |i| matches!(i, Instruction::BackendCall { backend, method, .. } 
                if backend == "math" && method == "sqrt")
        ));
    }

    #[test]
    fn compile_list_literal() {
        let source = "[1, 2, 3, 4, 5]";
        let result = Compiler::compile(source).unwrap();
        
        // Should have NewList instruction
        assert!(result.bytecode.main_instructions.iter().any(
            |i| matches!(i, Instruction::NewList(5))
        ));
    }

    #[test]
    fn compile_map_literal() {
        let source = r#"{"name": "Matter", "version": 1}"#;
        let result = Compiler::compile(source).unwrap();
        
        // Should have NewMap instruction
        assert!(result.bytecode.main_instructions.iter().any(
            |i| matches!(i, Instruction::NewMap(2))
        ));
    }

    #[test]
    fn compile_nested_expressions() {
        let source = "(1 + 2) * (3 - 4)";
        let result = Compiler::compile(source).unwrap();
        
        // Should compile without errors
        assert!(!result.bytecode.main_instructions.is_empty());
    }

    #[test]
    fn compile_event_handler() {
        let source = r#"
            on button_click {
                let x = 1
            }
        "#;
        let result = Compiler::compile(source).unwrap();
        
        // Should have event handler
        assert!(result.bytecode.event_handlers.contains_key("button_click"));
    }

    #[test]
    fn compile_print_statement() {
        let source = r#"print(42)"#;
        let result = Compiler::compile(source).unwrap();
        
        // Should have Print instruction
        assert!(result.bytecode.main_instructions.iter().any(
            |i| matches!(i, Instruction::Print)
        ));
    }

    #[test]
    fn end_to_end_hello_world() {
        let source = r#"print("Hello, World!")"#;
        let result = Compiler::compile(source);
        
        // Should compile successfully
        assert!(result.is_ok());
        let bytecode = result.unwrap().bytecode;
        
        // Should have instructions
        assert!(!bytecode.main_instructions.is_empty());
        
        // Should have string constant
        assert!(bytecode.constants.iter().any(
            |c| matches!(c, matter_bytecode::Constant::String(s) if s == "Hello, World!")
        ));
    }

    #[test]
    fn compile_arithmetic() {
        let source = "1 + 2 * 3 - 4 / 2";
        let result = Compiler::compile(source);
        
        // Should compile successfully
        assert!(result.is_ok());
    }

    #[test]
    fn compile_comparison() {
        let source = "1 < 2 && 3 >= 2 || 4 == 4";
        let result = Compiler::compile(source);
        
        // Should compile successfully
        assert!(result.is_ok());
    }

    #[test]
    fn constant_deduplication() {
        let source = "let x = 42\nlet y = 42\nlet z = 42";
        let result = Compiler::compile(source).unwrap();
        
        // BytecodeBuilder already does constant deduplication
        let count_42 = result.bytecode.constants.iter()
            .filter(|c| matches!(c, matter_bytecode::Constant::Int(42)))
            .count();
        assert_eq!(count_42, 1); // Only one instance of 42
    }

    #[test]
    fn compile_struct_definition() {
        let source = r#"
            struct Point {
                x: Int,
                y: Int
            }
        "#;
        let result = Compiler::compile(source);
        
        // Should compile without errors
        assert!(result.is_ok());
    }

    #[test]
    fn compile_match_statement() {
        let source = r#"
            let x = 1
            if x == 1 {
                let y = "one"
            }
        "#;
        let result = Compiler::compile(source);
        
        // Should compile without errors (match might not be fully supported yet)
        assert!(result.is_ok());
    }
}
